### ISSUE TITLE
riskmapjnr display issue

### ISSUE THREAD

**Issue by nbipul** [ghislainv/riskmapjnr#1]
I have installed the riskmap package as per the procedure.
However, I am getting following message when setting a virtual environment

(conda-rmj) C:\Users\Asdfhg>riskmapjnr
 no display found. Using non-interactive Agg backend
# riskmapjnr: Map of deforestation risk following JNR methodology.
# https://ecology.ghislainv.fr/riskmapjnr
# riskmapjnr version 0.2.

The above message is not allowing the tool to function properly, is there any help that I can get on this particular issue. I am a intermediate user of python.

Thank you

**Comment by ghislainv** [comment]
Hi @nbipul,
Thanks for using `riskmapjnr` and for reporting an issue. Commit  https://github.com/ghislainv/riskmapjnr/commit/4ce4bf3f29ba3216a5b3a923ff936848fb96a7cd should solve the problem. It will be included in future versions of the package. You can just install the development version for now using:
`pip install https://github.com/ghislainv/riskmapjnr/archive/master.zip`
Best regards
