### ISSUE TITLE
don't manage to run the lib on a FCC derived from GEE

### ISSUE THREAD

**Issue by 12rambau** [ghislainv/riskmapjnr#3]
# details

Hi @ghislainv, 

I'm trying to run the riskmapjnr in a module. before building up the interface I would like to create a running notebook using some GEE based map for the forest cover change (namely TMF and hansen&al. This is the current stage of dev: https://github.com/12rambau/riskmapjnr/blob/main/riskmapjnr.ipynb

when I try to run it on SEPAL I get some small deprecation error (not very important at the moment) but I get a strange error when running `rmj.makemap`:

```
File ~/.local/lib/python3.8/site-packages/riskmapjnr/dist_edge_threshold.py:226, in dist_edge_threshold(fcc_file, defor_values, dist_file, dist_bins, tab_file_dist, fig_file_dist, figsize, dpi, blk_rows, verbose)
    222 res_df.to_csv(tab_file_dist, sep=",", header=True,
    223               index=False, index_label=False)
    225 # Distance and percentage for 99% threshold
--> 226 index_thresh = np.nonzero(res_df["perc"].values > 99)[0][0]
    227 dist_thresh = res_df.loc[index_thresh, "distance"]
    228 perc_thresh = np.around(res_df.loc[index_thresh, "perc"], 2)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

Could you simply try to run my notebook from your side and let me know if you get the same error ? (I tried on your favorite AOI: guadeloupe). I think you just need to install ``sepal-ui``.

# Side note

I extracted the GADM interface from sepal-ui and created a small lib out of it. As you run many things out of GEE, you might be interested to get administrative geometries on the fly as a geodataframe: 

 https://pygadm.readthedocs.io/en/stable/

**Comment by ghislainv** [comment]
Hi @12rambau. Thanks for your feedback. I'll have a look and come back to you as soon as possible.

**Comment by ghislainv** [comment]
@12rambau And congrats for the `pygadm` package. Very useful !

**Comment by ghislainv** [comment]
@12rambau I am trying to run the notebook. What is the `component` package you are importing?

**Comment by 12rambau** [comment]
@ghislainv it's the `component` folder next to the notebook so to run it you need to pull the whole repository. I think I use it only for the `result_dir` parameter at the moment so you can hard code anything else in the cell.

**Comment by ghislainv** [comment]
Hi @12rambau, 

I was able to reproduce the error. It is due to the fact that the format of the `fcc_file` is not correct.
1. `fcc_file` must be projected (in a different CRS than lat/long) so that `gdal_proximity()` can be used to compute euclidean distance. I have added this point to the documentation.
2. `fcc_file` must have the following values: 1: first period deforestation, 2: second period deforestation, 3: remaining forest at the end of the second period. **No data value must be 0 (zero)**.
In your example, -128 is used as nodata value and 0 is used for non-forested land.

Try to use this format for the `fcc_file` and tell me if you are able to run the `makemap()` function of the `riskmapjnr` package.

Regards,

Ghislain

**Comment by ghislainv** [comment]
@12rambau, one additional note. In the notebook you provide, when using `sepal-ui`, the AOI for Guadeloupe is incorrect and includes other islands (Saint Martin and Saint Barthelemy).

**Comment by 12rambau** [comment]
> the AOI for Guadeloupe is incorrect and includes other islands (Saint Martin and Saint Barthelemy).

FAO GAUL  2015 is way to old and full of bugs. but FAO don't want to update it on GEE so I don't have other solutions (use pygadm from your side ;-) )

> fcc_file must be projected (in a different CRS than lat/long) so that gdal_proximity() can be used to compute euclidean distance. I have added this point to the documentation.

I will do that but isn't it dangerous to expect it from users? Would it be instead possible to detect the projetion of the image and use rioxarray internally to reproject the dataset? 

> In your example, -128 is used as nodata value and 0 is used for non-forested land.

I will set 0 everywhere !

**Comment by ghislainv** [comment]
@12rambau, regarding the projection, it is difficult to choose a projection in place of the user. What we can do is raising an error and a message if the file is in latlong.

**Comment by 12rambau** [comment]
That would be a perfect start. from my end I used "EPSG:3857" which seems to do the job nearly everywhere. using your inputs It worked. 

I leave it open for the warning/error

**Comment by ghislainv** [comment]
I have added checks for the `fcc_file` (commit https://github.com/ghislainv/riskmapjnr/commit/bf9c98b1ddc8e0e92b5dfb13913d86665e1fb7ba).

EPSG:3857 (or any global projection) should be avoided as they impose strong distortion of country shapes and thus do not conserve local distances. Local projections should be preferred.

**Comment by 12rambau** [comment]
what is the best projection system in the riskmajnr method ?
- Those that minimize distortion in shape are called conformal.
- Those that minimize distortion in distance are known as equidistant.
- Those that minimize distortion in area are known as equal-area.
- Those minimizing distortion in direction are called true-direction projections.

also, note that the current implementation is refusing 3857 as an input as it's derived from 4326...

**Comment by ghislainv** [comment]
@12rambau Best projections in the riskmapjnr method are those that minimize both distortion in areas and distances as the two are computed in the JNR methodology (deforestation areas and distance to forest edge). That's why it is preferable to use a local CRS (UTM for example or any official CRS for the jurisdiction considered).
