### ISSUE TITLE
pool is never joined

### ISSUE THREAD

**Issue by 12rambau** [ghislainv/riskmapjnr#5]
when run in parralel, Pool's `async-methods` return objects which are conceptually ["explicit futures"](https://en.wikipedia.org/wiki/Futures_and_promises#Implicit_vs._explicit), you need to call .get() to await and receive the actual result which is exactly what you did. On the other hand, before going any further in your code you also need to close and join the pool. Which is not done here: https://github.com/ghislainv/riskmapjnr/blob/96d33ee44a7527ee9d1fd27030d3369d1cc1d74b/riskmapjnr/makemap.py#L430

A call to the method in a script will execute next command before all the runners have finished: 

```python
results_makemap = rmj.makemap(**kwargs)

# add the results in the textfields 
ws_hat = results_makemap["ws_hat"]
m_hat = results_makemap["m_hat"]
dist_thresh = results_makemap["dist_thresh"]
```

will return: 
```
UnboundLocalError: local variable 'results_makemap' referenced before assignment
```

Is there other places where you used this method ? Happy to make a PR

## note
It's invisible in notebooks as tornado is making sure every promise is closed before finishing cell computation.

**Comment by ghislainv** [comment]
Thank you @12rambau. That is the only place I use `pool()`. I let you make a PR so that your contribution appear in the `riskmapjnr` project. Adding `pool.close()` and `pool.join()` just after l. 430 should do the trick.

**Comment by 12rambau** [comment]
I'll test it on the application today before making the PR (I want to make sure it works)
